### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [kissx/packages#8]
- [ ] Rename `puke` to something "nicer".
- [ ] Move the package manager to its own repository.
- [ ] Allow multiple repositories to be used.
    - [ ] Have a variable similar to `$PATH`.
- [ ] Proper dependency resolver.
    - The goal is to avoid things like circular dependency in the packages themselves.
- [ ] Allow multiple packages to be interfaced with at once.
- [ ] Add a `contrib` repository for smaller example scripts to interface with the repository.

**Comment by dylanaraps** [comment]
Moved to https://github.com/kissx/kiss
